[project]
name = "deathmonopoly"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "dotenv>=0.9.9",
    "matplotlib>=3.10.7",
    "openai>=2.7.2",
    "pyside6>=6.10.0",
    "pytest>=9.0.1",
    "yfinance>=0.2.66",
]
